### ISSUE TITLE
error with cacheing

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#141]
this is probably related to changing image shapes to list from tuple in the info file

```
INFO:pizza_cutter.des_pizza_cutter._pizza_cutter:reserving mosaic images...
|--------------------| 0/1521   0% [elapsed: 00:00 left: ?]INFO:pizza_cutter.des_pizza_cutter._pizza_cutter:processing object 0
Traceback (most recent call last):
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/bin/des-pizza-cutter", line 4, in <module>
    __import__('pkg_resources').run_script('pizza-cutter==0.1.0', 'des-pizza-cutter')
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    exec(script_code, namespace, namespace)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/EGG-INFO/scripts/des-pizza-cutter", line 87, in <module>
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/EGG-INFO/scripts/des-pizza-cutter", line 83, in main
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_pizza_cutter.py", line 147, in make_des_pizza_slices
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_pizza_cutter.py", line 283, in _coadd_and_write_images
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_coadd_slices.py", line 424, in _coadd_slice_inputs
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_se_image.py", line 798, in resample
TypeError: unhashable type: 'list'
tilename: DES0039-3914
```

**Comment by beckermr** [comment]
Ahhh frack. The yaml was serializing with weird python stuff. We should add a conversion back to a tuple.

**Comment by esheldon** [comment]
if we try to read these outside of python then the apocalypse is probably upon us and we should worry about something else

I'm just gonna write them as tuples

**Comment by beckermr** [comment]
Mmmmmk. We should put conversion checks here in case someone feeds lists

https://github.com/beckermr/pizza-cutter/blob/master/pizza_cutter/des_pizza_cutter/_load_info.py#L74
