### ISSUE TITLE
error with some piff wcs/pixmappy 

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#160]
```
(pizza) [esheldon@astro0010 test-pizza-cutter] less /data/esheldon/tmp/pizza-batch/des-pizza-slices-y3-v02/make-DES0029-6122-r.yaml.wqlog
executing on host: astro0003 with pid: 25921
tilename: DES0029-6122
band: r
loading PSF and WCS data...
output meds file: /astro/u/astrodat/data/DES/meds/des-pizza-slices-y3-v02/DES0029-6122/DES0029-6122_r_des-pizza-slices-y3-v02_meds-pizza-slices.fits
making pizza slices!
^M|--------------------| 0/1521   0% [elapsed: 00:00 left: ?]Traceback (most recent call last):
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/bin/des-pizza-cutter", line 4, in <module>
    __import__('pkg_resources').run_script('pizza-cutter==0.1.0', 'des-pizza-cutter')
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    exec(script_code, namespace, namespace)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/EGG-INFO/scripts/des-pizza-cutter", line 87, in <module>
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/EGG-INFO/scripts/des-pizza-cutter", line 83, in main
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_pizza_cutter.py", line 147, in make_des_pizza_slices
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_pizza_cutter.py", line 253, in _coadd_and_write_images
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_coadd_slices.py", line 166, in _build_slice_inputs
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_se_image.py", line 234, in __init__
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_sky_bounds.py", line 71, in get_rough_sky_bounds
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_se_image.py", line 373, in image2sky
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/PixMapPy-0.2-py3.6.egg/pixmappy/GalSimWCS.py", line 120, in _radec
    ra, dec = self._wcs.toSky(x, y, c=c )
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/PixMapPy-0.2-py3.6.egg/pixmappy/PixelMapCollection.py", line 432, in toSky
    xw, yw = self.pmap(x1,y1,c)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/PixMapPy-0.2-py3.6.egg/pixmappy/PixelMapCollection.py", line 397, in __call__
    x,y = self.elements[0](x,y,c)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/PixMapPy-0.2-py3.6.egg/pixmappy/PixelMapCollection.py", line 399, in __call__
    x,y = el(x,y,c)
  File "/gpfs01/astro/workarea/esheldon/anaconda-dirs/miniconda3/envs/pizza/lib/python3.6/site-packages/PixMapPy-0.2-py3.6.egg/pixmappy/PixelMapCollection.py", line 370, in __call__
    raise ValueError('ColorTerm requires non-null c argument')
ValueError: ColorTerm requires non-null c argument
```

**Comment by esheldon** [comment]
why does this wcs require a color term?

**Comment by beckermr** [comment]
No idea. It might be that we need to specify c = 0 somewhere.

**Comment by esheldon** [comment]
seems like it might be r only, the same tile is running in z

**Comment by beckermr** [comment]
we should ask gary and/or mike if they put color corrections in the r band psfs - the terms are bigger there apparently

**Comment by esheldon** [comment]
I checked my code in ngmixer, and it looks like I had to explicitly set the color term to zero
```
wcs = pixmappy.GalSimWCS(fname, exp=expnum, ccdnum=ccdnum)
wcs._color = 0.  # For now.  Revisit when doing color-dependent PSF.
```

**Comment by esheldon** [comment]
we are not doing "color-dependent PSF", so we should do this.

I'm surprised it isn't done automatically within the piff

**Comment by esheldon** [comment]
that didn't work, still crashes

**Comment by beckermr** [comment]
hmmmmmm - try adding `c=0` to some of the calls?

**Comment by esheldon** [comment]
yeah, its because we are calling `_radec` directly, so we need to set c by hand
