### ISSUE TITLE
assert failing on DES example

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#38]
It is this assert in des_pizza_cutter/_coadd_slices.py line 502
`assert _size <= psf_box_size`

```
reserving mosaic images...
 10%|███████████████████▋                                                                                                                                                                              | 154/1521 [24:27<2:23:21,  6.29s/it]Traceback (most recent call last):
  File "/home/esheldon/miniconda3/envs/easyaccess/bin/des-pizza-cutter", line 4, in <module>
    __import__('pkg_resources').run_script('pizza-cutter==0.1.0', 'des-pizza-cutter')
  File "/home/esheldon/miniconda3/envs/easyaccess/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/esheldon/miniconda3/envs/easyaccess/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/home/esheldon/miniconda3/envs/easyaccess/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/EGG-INFO/scripts/des-pizza-cutter", line 93, in <module>
  File "/home/esheldon/miniconda3/envs/easyaccess/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/esheldon/miniconda3/envs/easyaccess/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/esheldon/miniconda3/envs/easyaccess/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/esheldon/miniconda3/envs/easyaccess/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/esheldon/miniconda3/envs/easyaccess/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/EGG-INFO/scripts/des-pizza-cutter", line 89, in main
  File "/home/esheldon/miniconda3/envs/easyaccess/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_pizza_cutter.py", line 118, in make_des_pizza_slices
  File "/home/esheldon/miniconda3/envs/easyaccess/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_pizza_cutter.py", line 223, in _coadd_and_write_images
  File "/home/esheldon/miniconda3/envs/easyaccess/lib/python3.6/site-packages/pizza_cutter-0.1.0-py3.6.egg/pizza_cutter/des_pizza_cutter/_coadd_slices.py", line 502, in _coadd_slice_inputs
AssertionError

```

**Comment by esheldon** [comment]
the command was
```
des-pizza-cutter  --config=/home/esheldon/git/pizza-cutter/config_files/des-pizza-slices.yaml --tilename=DES0225-1041 --band=g --output-path=slices/ --seed=314159
```

**Comment by beckermr** [comment]
I'm redoing the internals here so probably not worth fixing this until that is done.

**Comment by esheldon** [comment]
Also that assertion should have a string message for easier interpretation of the problem
